implement footer info
aemsites/alshaya-hm pull request #40
Opened 2024-04-12 16:05 UTC by noelruiz34

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #[<gh-issue-id>](https://github.com/aemsites/alshaya-hm/issues/9)

Test URLs:
- Before: https://main--alshaya-hm--aemsites.hlx.page/
- After: https://footer-info--alshaya-hm--aemsites.hlx.page/

2024-04-15 09:32 UTC, duynguyen commented on blocks/footer/footer.css
> +.footer > div .section:last-child ul {
do we need the footer info content to be a list? doesn't normal paragraph content just work?

2024-04-15 13:00 UTC, noelruiz34 commented on blocks/footer/footer.css
> +.footer > div .section:last-child ul {
Is there a performance impact using a list? I used bullets in the doc [here](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BB3CDFA52-436E-438F-AA0E-3507804FC2D9%7D&file=footer.docx&action=default&mobileredirect=true) 

I think using list might also be necessary to handle desktop to mobile view as there is some reordering in the mobile view.

2024-04-17 13:03 UTC, duynguyen requested changes
thanks @noelruiz34 . a few minor comments

2024-04-17 13:03 UTC, duynguyen commented on blocks/footer/footer.css
> +  .footer .section.footer-info p:nth-child(6) {
the order of the last 3 elements is tricky.
IMO relying on the order of child elements is not stable though, esp. those are 6th, 7th, 8th child.
can we make the last 3 elements in the footer one section and name it "footer copyright"?
then the css selector becomes:
```
.footer .section.footer-copyright p {
  order: 2;
}
.footer .section.footer-copyright p:last-child {
  order: 1;
}
```
so last child is the social media links.
with this we can also tailor the font-size of this section, which appears to be a bit larger than the info above.

2024-04-17 14:16 UTC, noelruiz34 commented on blocks/footer/footer.css
> +  a {
These are nested selectors, so it's the same as `.footer .section.footer-info p a` I used this because the base path is all the same for these elements so imo it's a bit cleaner this way. Is it preferred to break all of these up?

2024-04-17 14:42 UTC, duynguyen commented on blocks/footer/footer.css
> +  a {
I see, thanks for clarifying.

2024-04-17 18:29 UTC, noelruiz34 commented on blocks/footer/footer.css
> +  .footer .section.footer-info p:nth-child(6) {
Updated as a separate section

2024-04-18 12:47 UTC, merged